### ISSUE TITLE
халло фром лор ::)

### ISSUE THREAD

**Issue by blogdron** [eddyem/eddys_snippets#1]
Эдик, а лицензия то какая на твою имплементацию json? И залогинься уже на лоре по нормпльному, а то люди как на рыбалке тебя из  тедов вылавнивают, рыба ты эдокая :D

**Comment by eddyem** [comment]
Привет!
Везде GPLv3. Логиниться на ЛОРе не собираюсь.

**Comment by blogdron** [comment]
Тебе надо срочно сюда https://www.linux.org.ru/news/opensource/13260661 если ты ещё не в курсе веселья

**Comment by eddyem** [comment]
Насрать: у меня все клонировано на сосфорже, битбакете и гитлабе. 
Если гитхаб охуел вконец и пошлет нахуй свободные лицензии, есть еще резерв.
Ну, а если и там пошлют, то все равно что-нибудь да появится! Не будет же Линус ведро на своем айфоне пушить...

**Comment by blogdron** [comment]
И то верно.
